### ISSUE TITLE
 Implement Loan Application Feature(Issue 10)

### ISSUE THREAD

**Issue by Wendymackennah** [Wendymackennah/mo-bank#11]
### Implement Loan Application Feature
*****
### Description

- [ ] Allow users to apply for loans directly through the app.

### Tasks

- [ ]  Create a loan application form with eligibility checks.
- [ ]  Integrate backend API for submitting loan applications.
- [ ]  Display loan status and repayment schedules.
- [ ]  Add user feedback (approval/rejection messages).
